// Please do not change these values. If you change these values, sitemap will generate wrong pages.
export const pages = [
  "about-us",
  "ai-domain-generator",
  "advanced-ai-domain-name-generator",
  "best-dedicated-hosting",
  "best-reseller-hosting",
  "best-shared-hosting",
  "best-vps-hosting",
  "best-woocommerce-hosting",
  "best-wordpress-hosting",
  "best-wordpress-plugins",
  "best-wordpress-themes",
  "blog",
  "bulk-domain-checker",
  "bulk-domain-location-checker",
  "bulk-domain-whois-checker",
  // "bulk-web-hosting-checker",
  "contact-us",
  "coupons-and-promo",
  "dns-checker",
  "domain-whois-info",
  "hosting-server-location",
  "random-letter-generator",
  "random-word-generator",
  "reverse-ip-checker",
  "saved-domains",
  "top-ten-hosting",
  // "who-is-hosting",
];
